version: '3.7'

services:
  gayaz_postgres_db:
    image: postgres:latest
    container_name: gayaz_db
    restart: always
    ports:
      - 6000:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=my_database
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: